name: Monitor sites

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-sites:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar monitoreo
        run: curl -X GET https://sensor-git-main-beneficios.vercel.app/api/check-sites
